---
- hosts: traefik-clients
  connection: local
  gather_facts: false
  tasks:
    - name: Create Traefik route53 user
      iam:
        aws_access_key: "{{access}}"
        aws_secret_key: "{{secret}}"
        iam_type: user
        name: "traefik-route53-{{ inventory_hostname }}"
        state: present
        access_key_state: create
      connection: local
      register: credentials

    - name: AWS_ACCESS_KEY
      debug:
        var: credentials.user_meta.access_keys[0].access_key_id
      when: credentials.changed

    - name: AWS_SECRET_KEY
      debug:
        var: credentials.user_meta.access_keys[0].secret_access_key
      when: credentials.changed

    - name: create policy facts
      set_fact:
        policy_json: " {{ lookup( 'template', 'traefik-route53-policy.json.j2') |to_json }} "

    - name: Create Policy for Restic user
      iam_policy:
        aws_access_key: "{{access}}"
        aws_secret_key: "{{secret}}"
        iam_type: user
        iam_name: "traefik-route53-{{ inventory_hostname }}"
        policy_name: "traefik-route53-{{ inventory_hostname }}"
        state: present
        policy_json: "{{ policy_json }}"
      connection: local

